# vim: set ts=2 sw=2 tw=0 fo=cnqoj
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2
project_name: note

env:
  - CGO_ENABLED=1

before:
  hooks:
    - go install github.com/mattn/go-sqlite3

builds:
  - id: note-linux
    binary: note
    env:
      - CC=x86_64-linux-gnu-gcc
    goarch:
      - amd64
    goos:
      - linux
    flags:
      - -trimpath
    ldflags:
      - -s -w -X 'github.com/bdazl/note/cmd.Version={{ .Version }}'

  #- id: note-darwin
  #  binary: note
  #  env:
  #    - CC=oa64-clang
  #  goarch:
  #    - amd64
  #  goos:
  #    - darwin
  #  flags:
  #    - -trimpath
  #  ldflags:
  #    - -s -w -X 'github.com/bdazl/note/cmd.Version={{ .Version }}'

  - id: note-windows
    binary: note
    env:
      - CC=x86_64-w64-mingw32-gcc
    goarch:
      - amd64
    goos:
      - windows
    flags:
      - -trimpath
    ldflags:
      - -s -w -X 'github.com/bdazl/note/cmd.Version={{ .Version }}'

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: "note_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "note_{{ .Version }}_checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^chore:"
      - "^docs:"
      - "^test:"

release:
  github:
    owner: bdazl
    name: note
  prerelease: auto
  mode: replace
  draft: true
