#!/bin/bash
set -ex

DOCS=$(realpath $(dirname "${BASH_SOURCE[0]}"))

OUT=${1:-$DOCS/gifs}
DOCKER=${DOCKER:-podman}
VHS_IMAGE=${VHS_IMAGE:-note-vhs:latest}

mkdir -p "$OUT"

$DOCKER run -d --name tmp --entrypoint '["/bin/sleep", "2"]' $VHS_IMAGE
$DOCKER cp tmp:/vhs/out/. "$OUT"
$DOCKER stop -t 0 tmp
$DOCKER rm tmp
